// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqibwynpmnwupsdkpzdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxaWJ3eW5wbW53dXBzZGtwemRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NzkzNjEsImV4cCI6MjA1MTE1NTM2MX0.5kK3c-J-satzkAYjcyiaTLoa8AyvT7TY-sRIlWCK1PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);